// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(InventarioContext))]
    [Migration("20260826205431_inicio")]
    partial class inicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Created_at")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Calle Falsa 123",
                            Created_at = new DateTimeOffset(new DateTime(2026, 8, 26, 17, 54, 31, 167, DateTimeKind.Unspecified).AddTicks(5016), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "12345678",
                            Firstname = "Juan",
                            IsDeleted = false,
                            Lastname = "Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Avenida Siempre Viva 456",
                            Created_at = new DateTimeOffset(new DateTime(2026, 8, 26, 17, 54, 31, 167, DateTimeKind.Unspecified).AddTicks(5047), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "87654321",
                            Firstname = "María",
                            IsDeleted = false,
                            Lastname = "González"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Callejón del Beso 789",
                            Created_at = new DateTimeOffset(new DateTime(2026, 8, 26, 17, 54, 31, 167, DateTimeKind.Unspecified).AddTicks(5049), new TimeSpan(0, -3, 0, 0, 0)),
                            Dni = "11223344",
                            Firstname = "Pedro",
                            IsDeleted = false,
                            Lastname = "López"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
